development: &development
  adapter: postgresql
  database: aid_go
  encoding: utf8
  host: localhost
  port: 5432
  username:
  password:
  pool: 5

test:
  <<: *development

production:
  <<: *development
